package temporal:nexus@1.0.0;

world system {
  export on-complete-request;
}

interface on-complete-request {
  use nexus:temporal-types/model@1.0.0.{
    failure,
    placeholder,
  };

  /// @nexus.type-parameter
  type source-context-t = placeholder;

  /// @nexus.type-parameter
  type output-t = placeholder;

  /// @nexus.proto "temporal.api.notificationservice.v1.OnCompleteRequest.result"
  variant on-complete-request-result {
    success(output-t),
    failure(failure),
  }

  /// @nexus.proto "temporal.api.notificationservice.v1.OnCompleteRequest"
  record on-complete-request {
    %result: on-complete-request-result,
    source-context: source-context-t,
  }

  /// @nexus.proto "temporal.api.notificationservice.v1.OnCompleteResponse"
  record on-complete-response {
  }
}
