package main

import (
	"context"
	"errors"
	"flag"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/bufbuild/protocompile/experimental/ast/edit"
	"github.com/bufbuild/protocompile/experimental/ast/printer"
	"github.com/bufbuild/protocompile/experimental/incremental"
	"github.com/bufbuild/protocompile/experimental/incremental/queries"
	"github.com/bufbuild/protocompile/experimental/ir"
	"github.com/bufbuild/protocompile/experimental/report"
)

const (
	apiNextPrefix   = "temporal/api_next/"
	stableAPIPrefix = "temporal/api/"

	experimentalTagsPath = apiNextPrefix + "protometa/v1/experimental.proto"

	generatedHeader = "// Code generated by generate-stable-protos. DO NOT EDIT. \n // @generated \n\n"
)

func main() {
	root := flag.String("root", ".", "directory holding the proto tree; also the sole import path")
	outDir := flag.String("out", "", "directory to write the projected tree into (defaults to -root/ as api is still different from api_next)")
	flag.Parse()

	if info, err := os.Stat(*root); err != nil || !info.IsDir() {
		fmt.Fprintf(os.Stderr, "-root %q must be an existing directory\n", *root)
		os.Exit(1)
	}
	if *outDir == "" {
		*outDir = *root
	}

	if err := stableProtosGenerator(*root, *outDir); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func stableProtosGenerator(root, outDir string) error {
	ctx := context.Background()
	paths, err := getAPINextPaths(root)
	if err != nil {
		return err
	}
	if len(paths) == 0 {
		return fmt.Errorf("no protos found under %q", filepath.Join(root, apiNextPrefix))
	}

	strippedOrder, strippedProtos, err := stripDrafts(ctx, root, paths)
	if err != nil {
		return err
	}

	// import stripping has to happen after the draft-tagged declarations are deleted
	// because unused imports are only detectable after it is re-rendered
	stableProtos, err := organizeImports(ctx, root, strippedOrder, strippedProtos)
	if err != nil {
		return err
	}

	addGeneratedHeader(stableProtos)

	if err := verifyGeneratedProtos(ctx, root, stableProtos); err != nil {
		return err
	}

	return writeFiles(outDir, stableProtos)
}

func addGeneratedHeader(protos map[string]string) {
	for path, text := range protos {
		protos[path] = generatedHeader + text
	}
}

func stripDrafts(ctx context.Context, root string, paths []string) ([]string, map[string]string, error) {
	session := &ir.Session{}
	opener := baseOpener(root)

	// first, lower the api_next set into ir
	lowerQueries := make([]incremental.Query[*ir.File], len(paths))
	for i, p := range paths {
		lowerQueries[i] = queries.IR{Opener: opener, Session: session, Path: p}
	}
	results, err := lowerFiles(ctx, lowerQueries...)
	if err != nil {
		return nil, nil, fmt.Errorf("lower api_next corpus: %w", err)
	}

	// need to iterate to find the experimental proto- also check
	// for errors while iterating so it doesnt have to be repeated
	byPath := make(map[string]*ir.File, len(paths))
	for i, p := range paths {
		if results[i].Fatal != nil {
			return nil, nil, fmt.Errorf("%s: %w", p, results[i].Fatal)
		}
		irFile := results[i].Value
		if got := irFile.Path(); got != p {
			return nil, nil, fmt.Errorf("internal error: incremental.Run result %d has path %q, expected %q", i, got, p)
		}
		byPath[p] = irFile
	}

	experimentalFile, ok := byPath[experimentalTagsPath]
	if !ok {
		return nil, nil, fmt.Errorf("%s not found in the corpus; cannot discover the draft-tag extension set", experimentalTagsPath)
	}
	tags, err := getDraftTags(experimentalFile)
	if err != nil {
		return nil, nil, err
	}

	stableOrder := make([]string, 0, len(paths))
	protoTexts := make(map[string]string, len(paths))
	for p, irFile := range byPath {
		// skip experimental.proto itself
		if p == experimentalTagsPath {
			continue
		}

		dels := findDraftNodes(tags, irFile)
		edits := make([]edit.Edit, len(dels))
		for j, d := range dels {
			edits[j] = edit.Edit{Kind: edit.KindDelete, Target: d}
		}
		if err := edit.ApplyEdits(irFile.AST(), edits); err != nil {
			return nil, nil, fmt.Errorf("delete draft declarations: %s: %w", p, err)
		}
		protoText, err := printer.PrintFile(
			printer.Options{
				Format: true,
				//TODO: check if the buf formatter rules can just get pulled into a custom formatter
				Formatting: printer.Legacy(),
			},
			irFile.AST(),
		)
		if err != nil {
			return nil, nil, fmt.Errorf("print %s: %w", p, err)
		}

		protoTexts[p] = protoText
		stableOrder = append(stableOrder, p)
	}
	return stableOrder, protoTexts, nil
}

// strip unused imports and rename import to stable (api_next -> api)
func organizeImports(ctx context.Context, root string, order []string, texts map[string]string) (map[string]string, error) {
	session := &ir.Session{}
	opener := memOpener(root, texts)

	relowerQueries := make([]incremental.Query[*ir.File], len(order))
	for i, p := range order {
		relowerQueries[i] = queries.IR{Opener: opener, Session: session, Path: p}
	}
	results, err := lowerFiles(ctx, relowerQueries...)
	if err != nil {
		return nil, fmt.Errorf("re-lower draft-stripped corpus: %w", err)
	}

	stableTexts := make(map[string]string, len(order))
	for i, p := range order {
		if results[i].Fatal != nil {
			return nil, fmt.Errorf("%s: %w", p, results[i].Fatal)
		}
		irFile := results[i].Value

		// Collect the api_next import paths that SURVIVE pruning in the
		// same loop that decides what to prune, rather than re-deriving
		// them from file.Imports() afterward: once importDels is applied
		// below, the deleted imports' Decls are gone from the AST, but
		// file.Imports() itself is a snapshot from before the edit and
		// would still happily report them, so re-querying after the fact
		// would silently include paths that no longer appear in the
		// printed text. Collecting the survivors here, before any edit
		// happens, is the only interpretation that can't drift from what
		// ApplyEdits actually does.
		var importDels []edit.Edit
		var survivingNextPaths []string
		for j := 0; j < irFile.Imports().Len(); j++ {
			imp := irFile.Imports().At(j)
			if !imp.Used && !imp.Decl.IsZero() {
				importDels = append(importDels, edit.Edit{Kind: edit.KindDelete, Target: imp.Decl.AsAny()})
				continue
			}
			if path := imp.Path(); strings.HasPrefix(path, apiNextPrefix) {
				survivingNextPaths = append(survivingNextPaths, path)
			}
		}
		if err := edit.ApplyEdits(irFile.AST(), importDels); err != nil {
			return nil, fmt.Errorf("prune imports: %s: %w", p, err)
		}
		protoText, err := printer.PrintFile(
			printer.Options{
				Format:     true,
				Formatting: printer.Legacy(),
			},
			irFile.AST(),
		)
		if err != nil {
			return nil, fmt.Errorf("print %s: %w", p, err)
		}
		stableTexts[stablePath(p)] = rewriteImportPaths(protoText, survivingNextPaths)
	}
	return stableTexts, nil
}

// re-lower one more time to ensure there are no compilation issues
func verifyGeneratedProtos(ctx context.Context, root string, stableTexts map[string]string) error {
	session := &ir.Session{}
	opener := memOpener(root, stableTexts)

	paths := make([]string, 0, len(stableTexts))
	for p := range stableTexts {
		paths = append(paths, p)
	}
	sort.Strings(paths)

	lowerQueries := make([]incremental.Query[*ir.File], len(paths))
	for i, p := range paths {
		lowerQueries[i] = queries.IR{Opener: opener, Session: session, Path: p}
	}
	results, err := lowerFiles(ctx, lowerQueries...)
	if err != nil {
		return fmt.Errorf("verify stable tree failed: %w", err)
	}
	var jErr error
	for i, r := range results {
		if r.Fatal != nil {
			jErr = errors.Join(jErr, fmt.Errorf("verification failed at file %q: %w", paths[i], r.Fatal))
		}
	}
	return jErr
}

func lowerFiles(ctx context.Context, lowerQueries ...incremental.Query[*ir.File]) ([]incremental.Result[*ir.File], error) {
	results, report, err := incremental.Run(ctx, incremental.New(), lowerQueries...)
	if err != nil {
		return nil, err
	}
	if text, hasErrors := errorDiagnostics(report); hasErrors {
		return nil, fmt.Errorf("diagnostics produced :\n%s", text)
	}
	return results, nil
}

func errorDiagnostics(r *report.Report) (renderText string, hasErrors bool) {
	for _, d := range r.Diagnostics {
		if d.Level() <= report.Error {
			hasErrors = true
			break
		}
	}
	if !hasErrors {
		return "", false
	}
	text, _, _ := (report.Renderer{}).RenderString(r)
	return text, true
}

func stablePath(path string) string {
	if path == experimentalTagsPath {
		return path
	}
	if rest, ok := strings.CutPrefix(path, apiNextPrefix); ok {
		return stableAPIPrefix + rest
	}
	return path
}

func writeFiles(dir string, files map[string]string) error {
	for path, text := range files {
		dest := filepath.Join(dir, filepath.FromSlash(path))
		if err := os.MkdirAll(filepath.Dir(dest), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(dest, []byte(text), 0o644); err != nil {
			return fmt.Errorf("write %q: %w", dest, err)
		}
	}
	return nil
}

func getAPINextPaths(root string) ([]string, error) {
	var sources []string
	dir := filepath.Join(root, filepath.FromSlash(apiNextPrefix))
	if err := filepath.WalkDir(dir, func(path string, entry fs.DirEntry, err error) error {
		if err != nil || entry.IsDir() || filepath.Ext(path) != ".proto" {
			return err
		}
		relative, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}
		sources = append(sources, filepath.ToSlash(relative))
		return nil
	}); err != nil {
		return nil, fmt.Errorf("walk %q: %w", dir, err)
	}
	sort.Strings(sources)
	return sources, nil
}

// rewriteImportPaths rewrites the surviving imports from api_next to api
func rewriteImportPaths(text string, nextPaths []string) string {
	for _, path := range nextPaths {
		text = strings.ReplaceAll(text, `"`+path+`"`, `"`+stablePath(path)+`"`)
	}
	return text
}
