package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"regexp"
	"sort"
	"strings"
	"text/template"

	"golang.org/x/tools/imports"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protodesc"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/types/descriptorpb"

	protometa "go.temporal.io/api/protometa/v1"
)

const requestHeaderFile = "../../proxy/request_header.go"

const requestHeaderTemplateText = `
// Code generated by proxygenerator; DO NOT EDIT.

package proxy

import (
	"context"
	"errors"
	"fmt"

	"google.golang.org/grpc/metadata"
	"google.golang.org/protobuf/proto"
	{{range $path, $alias := .Imports}}
	{{$alias}} "{{$path}}"
	{{end}}
)

// ExtractHeadersOptions contains options for extracting Temporal request headers.
type ExtractHeadersOptions struct {
	// Request is the proto message to extract headers from. Required.
	Request proto.Message

	// ExistingMetadata contains existing metadata to check for duplicates.
	// If provided, headers that already exist will not be added again.
	// If nil, no duplicate checking is performed.
	ExistingMetadata metadata.MD
}

// ExtractTemporalRequestHeaders extracts field values from request messages and returns
// them as a slice of key-value pairs suitable for use with metadata.AppendToOutgoingContext.
// Returns nil if no headers should be set.
func ExtractTemporalRequestHeaders(ctx context.Context, opts ExtractHeadersOptions) ([]string, error) {
	if opts.Request == nil {
		return nil, errors.New("request cannot be nil")
	}

	var headers []string

	// Set namespace header if present and not already exists
	if len(opts.ExistingMetadata.Get("temporal-namespace")) == 0 {
		if nsReq, ok := opts.Request.(interface{ GetNamespace() string }); ok {
			if ns := nsReq.GetNamespace(); ns != "" {
				headers = append(headers, "temporal-namespace", ns)
			}
		}
	}

	// Set headers from proto annotations
	switch r := opts.Request.(type) {
{{range .Methods}}	case *{{.PackageAlias}}.{{.RequestType}}:
{{range .Headers}}{{.Code}}{{end}}
{{end}}	}

	return headers, nil
}
`

var requestHeaderTemplate = template.Must(template.New("request_header").Parse(requestHeaderTemplateText))

type requestHeaderTemplateInput struct {
	Methods []methodHeaderInfo
	Imports map[string]string // map[importPath]alias
}

type methodHeaderInfo struct {
	PackageAlias string
	RequestType  string
	Headers      []headerInfo
}

type headerInfo struct {
	Code string
}

func generateRequestHeader(cfg config) error {
	data, err := os.ReadFile(cfg.descriptorPath)
	if err != nil {
		return fmt.Errorf("reading descriptor set: %w", err)
	}

	var fdSet descriptorpb.FileDescriptorSet
	if err := proto.Unmarshal(data, &fdSet); err != nil {
		return fmt.Errorf("unmarshalling descriptor set: %w", err)
	}

	files, err := protodesc.NewFiles(&fdSet)
	if err != nil {
		return fmt.Errorf("creating file registry: %w", err)
	}

	var allMethods []methodHeaderInfo
	importsMap := make(map[string]string) // map[importPath]alias

	files.RangeFiles(func(fd protoreflect.FileDescriptor) bool {
		services := fd.Services()
		for i := 0; i < services.Len(); i++ {
			service := services.Get(i)
			methods, importPath, alias, err := extractMethodHeaders(service)
			if err != nil {
				return false
			}

			if len(methods) > 0 && importPath != "" {
				importsMap[importPath] = alias
			}

			allMethods = append(allMethods, methods...)
		}
		return true
	})

	if err != nil {
		return err
	}

	// Sort methods alphabetically by RequestType for consistent output
	sort.Slice(allMethods, func(i, j int) bool {
		return allMethods[i].RequestType < allMethods[j].RequestType
	})

	buf := &bytes.Buffer{}
	err = requestHeaderTemplate.Execute(buf, requestHeaderTemplateInput{
		Methods: allMethods,
		Imports: importsMap,
	})
	if err != nil {
		return fmt.Errorf("executing template: %w", err)
	}

	src, err := imports.Process(requestHeaderFile, buf.Bytes(), nil)
	if err != nil {
		return fmt.Errorf("failed to process imports: %w", err)
	}

	src, err = format.Source(src)
	if err != nil {
		return fmt.Errorf("failed to format: %w", err)
	}

	if cfg.verifyOnly {
		currentSrc, err := os.ReadFile(requestHeaderFile)
		if err != nil {
			return fmt.Errorf("failed to read existing file: %w", err)
		}

		if !bytes.Equal(src, currentSrc) {
			return fmt.Errorf("generated file does not match existing file: %s", requestHeaderFile)
		}

		return nil
	}

	if err := os.WriteFile(requestHeaderFile, src, 0666); err != nil {
		return fmt.Errorf("failed to write file: %w", err)
	}

	return nil
}

func extractMethodHeaders(service protoreflect.ServiceDescriptor) ([]methodHeaderInfo, string, string, error) {
	var methods []methodHeaderInfo

	// Get the Go package info from the file descriptor
	fileDesc := service.ParentFile()
	goPackageOption := fileDesc.Options().(*descriptorpb.FileOptions).GetGoPackage()

	// Parse go_package option: "go.temporal.io/api/workflowservice/v1;workflowservice"
	// Format is "import/path;packagename" or just "import/path"
	parts := strings.Split(goPackageOption, ";")
	importPath := parts[0]
	var packageAlias string
	if len(parts) > 1 {
		packageAlias = parts[1]
	} else {
		// Use last part of import path as alias
		pathParts := strings.Split(importPath, "/")
		packageAlias = pathParts[len(pathParts)-1]
	}

	for i := 0; i < service.Methods().Len(); i++ {
		method := service.Methods().Get(i)
		opts := method.Options()
		if opts == nil {
			continue
		}

		if !proto.HasExtension(opts, protometa.E_RequestHeader) {
			continue
		}

		ext := proto.GetExtension(opts, protometa.E_RequestHeader)
		annotations, ok := ext.([]*protometa.RequestHeaderAnnotation)
		if !ok || len(annotations) == 0 {
			continue
		}

		requestTypeName := string(method.Input().Name())
		requestMsgDesc := method.Input()
		var headerInfos []headerInfo

		for _, annotation := range annotations {
			code, err := generateHeaderCode(annotation.GetHeader(), annotation.GetValue(), "r", requestMsgDesc)
			if err != nil {
				return nil, "", "", fmt.Errorf("failed to generate header code for %s.%s: %w", service.Name(), method.Name(), err)
			}
			headerInfos = append(headerInfos, headerInfo{Code: code})
		}

		methods = append(methods, methodHeaderInfo{
			PackageAlias: packageAlias,
			RequestType:  requestTypeName,
			Headers:      headerInfos,
		})
	}

	return methods, importPath, packageAlias, nil
}

func generateHeaderCode(headerName, valueTemplate, reqVar string, msgDesc protoreflect.MessageDescriptor) (string, error) {
	fieldPaths := parseValueTemplate(valueTemplate)

	if len(fieldPaths) == 0 {
		return fmt.Sprintf("\t\tif %q != \"\" && len(opts.ExistingMetadata.Get(%q)) == 0 {\n\t\t\theaders = append(headers, %q, %q)\n\t\t}", valueTemplate, headerName, headerName, valueTemplate), nil
	}

	if len(fieldPaths) > 1 {
		return "", fmt.Errorf("only one field interpolation is supported, found %d", len(fieldPaths))
	}

	fieldPath := fieldPaths[0]
	accessor, err := generateFieldAccessor(fieldPath, reqVar, msgDesc)
	if err != nil {
		return "", fmt.Errorf("failed to generate accessor for %s: %w", fieldPath, err)
	}

	finalValue := strings.Replace(valueTemplate, "{"+fieldPath+"}", "%s", 1)

	// Generate code that checks if the field value is non-empty and header doesn't exist before formatting and appending
	return fmt.Sprintf("\t\tif val := %s; val != \"\" && len(opts.ExistingMetadata.Get(%q)) == 0 {\n\t\t\theaders = append(headers, %q, fmt.Sprintf(%q, val))\n\t\t}",
		accessor, headerName, headerName, finalValue), nil
}

func generateFieldAccessor(fieldPath, varName string, msgDesc protoreflect.MessageDescriptor) (string, error) {
	parts := strings.Split(fieldPath, ".")
	accessor := varName
	currentMsg := msgDesc

	for _, part := range parts {
		field := currentMsg.Fields().ByName(protoreflect.Name(part))
		if field == nil {
			return "", fmt.Errorf("field %s not found in message %s", part, currentMsg.FullName())
		}

		goName := protoFieldToGoName(part)
		accessor = fmt.Sprintf("%s.Get%s()", accessor, goName)

		if field.Kind() == protoreflect.MessageKind && field.Message() != nil {
			currentMsg = field.Message()
		}
	}

	return accessor, nil
}

func parseValueTemplate(valueTemplate string) []string {
	re := regexp.MustCompile(`\{([^}]+)\}`)
	matches := re.FindAllStringSubmatch(valueTemplate, -1)

	fieldPaths := make([]string, 0, len(matches))
	for _, match := range matches {
		if len(match) > 1 {
			fieldPaths = append(fieldPaths, match[1])
		}
	}

	return fieldPaths
}

func protoFieldToGoName(protoName string) string {
	parts := strings.Split(protoName, "_")
	for i := range parts {
		if len(parts[i]) > 0 {
			parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
		}
	}
	return strings.Join(parts, "")
}

func getPackageName(service protoreflect.ServiceDescriptor) string {
	fullName := string(service.FullName())
	parts := strings.Split(fullName, ".")
	if len(parts) < 2 {
		return "unknown"
	}
	return parts[len(parts)-2]
}
