syntax = "proto3";

package temporal.api.nexusoperation.v1;

option go_package = "go.temporal.io/api/nexusoperation/v1;nexusoperation";
option java_package = "io.temporal.api.nexusoperation.v1";
option java_multiple_files = true;
option java_outer_classname = "MessageProto";
option ruby_package = "Temporalio::Api::NexusOperation::V1";
option csharp_namespace = "Temporalio.Api.NexusOperation.V1";

import "temporal/api/callback/v1/message.proto";

// CallbackInfo contains the state of a callback attached to a standalone Nexus operation.
message CallbackInfo {
    // Trigger for when the Nexus operation is completed, covering both success cases as
    // well as any type of failure.
    message OperationCompleted {}

    message Trigger {
        oneof variant {
            OperationCompleted operation_completed = 1;
        }
    }

    // Trigger for this callback.
    Trigger trigger = 1;
    // Common callback info.
    temporal.api.callback.v1.CallbackInfo info = 2;
}
