// Code generated by proxygenerator; DO NOT EDIT.

package proxy

import (
	"context"
	"errors"
	"fmt"

	"google.golang.org/grpc/metadata"
	"google.golang.org/protobuf/proto"

	workflowservice "go.temporal.io/api/workflowservice/v1"
)

// ExtractHeadersOptions contains options for extracting Temporal request headers.
type ExtractHeadersOptions struct {
	// Request is the proto message to extract headers from. Required.
	Request proto.Message

	// ExistingMetadata contains existing metadata to check for duplicates.
	// If provided, headers that already exist will not be added again.
	// If nil, no duplicate checking is performed.
	ExistingMetadata metadata.MD
}

// ExtractTemporalRequestHeaders extracts field values from request messages and returns
// them as a slice of key-value pairs suitable for use with metadata.AppendToOutgoingContext.
// Returns nil if no headers should be set.
func ExtractTemporalRequestHeaders(ctx context.Context, opts ExtractHeadersOptions) ([]string, error) {
	if opts.Request == nil {
		return nil, errors.New("request cannot be nil")
	}

	var headers []string

	// Set namespace header if present and not already exists
	if len(opts.ExistingMetadata.Get("temporal-namespace")) == 0 {
		if nsReq, ok := opts.Request.(interface{ GetNamespace() string }); ok {
			if ns := nsReq.GetNamespace(); ns != "" {
				headers = append(headers, "temporal-namespace", ns)
			}
		}
	}

	// Set headers from proto annotations
	switch r := opts.Request.(type) {
	case *workflowservice.DescribeActivityExecutionRequest:
		if val := r.GetActivityId(); val != "" && len(opts.ExistingMetadata.Get("temporal-resource-id")) == 0 {
			headers = append(headers, "temporal-resource-id", fmt.Sprintf("activity:%s", val))
		}
	case *workflowservice.DescribeWorkflowExecutionRequest:
		if val := r.GetExecution().GetWorkflowId(); val != "" && len(opts.ExistingMetadata.Get("temporal-resource-id")) == 0 {
			headers = append(headers, "temporal-resource-id", fmt.Sprintf("workflow:%s", val))
		}
	case *workflowservice.GetWorkflowExecutionHistoryRequest:
		if val := r.GetExecution().GetWorkflowId(); val != "" && len(opts.ExistingMetadata.Get("temporal-resource-id")) == 0 {
			headers = append(headers, "temporal-resource-id", fmt.Sprintf("workflow:%s", val))
		}
	case *workflowservice.GetWorkflowExecutionHistoryReverseRequest:
		if val := r.GetExecution().GetWorkflowId(); val != "" && len(opts.ExistingMetadata.Get("temporal-resource-id")) == 0 {
			headers = append(headers, "temporal-resource-id", fmt.Sprintf("workflow:%s", val))
		}
	case *workflowservice.PauseWorkflowExecutionRequest:
		if val := r.GetWorkflowId(); val != "" && len(opts.ExistingMetadata.Get("temporal-resource-id")) == 0 {
			headers = append(headers, "temporal-resource-id", fmt.Sprintf("workflow:%s", val))
		}
	case *workflowservice.PollActivityExecutionRequest:
		if val := r.GetActivityId(); val != "" && len(opts.ExistingMetadata.Get("temporal-resource-id")) == 0 {
			headers = append(headers, "temporal-resource-id", fmt.Sprintf("activity:%s", val))
		}
	case *workflowservice.QueryWorkflowRequest:
		if val := r.GetExecution().GetWorkflowId(); val != "" && len(opts.ExistingMetadata.Get("temporal-resource-id")) == 0 {
			headers = append(headers, "temporal-resource-id", fmt.Sprintf("workflow:%s", val))
		}
	case *workflowservice.RequestCancelActivityExecutionRequest:
		if val := r.GetActivityId(); val != "" && len(opts.ExistingMetadata.Get("temporal-resource-id")) == 0 {
			headers = append(headers, "temporal-resource-id", fmt.Sprintf("activity:%s", val))
		}
	case *workflowservice.RequestCancelWorkflowExecutionRequest:
		if val := r.GetWorkflowExecution().GetWorkflowId(); val != "" && len(opts.ExistingMetadata.Get("temporal-resource-id")) == 0 {
			headers = append(headers, "temporal-resource-id", fmt.Sprintf("workflow:%s", val))
		}
	case *workflowservice.ResetWorkflowExecutionRequest:
		if val := r.GetWorkflowExecution().GetWorkflowId(); val != "" && len(opts.ExistingMetadata.Get("temporal-resource-id")) == 0 {
			headers = append(headers, "temporal-resource-id", fmt.Sprintf("workflow:%s", val))
		}
	case *workflowservice.SignalWithStartWorkflowExecutionRequest:
		if val := r.GetWorkflowId(); val != "" && len(opts.ExistingMetadata.Get("temporal-resource-id")) == 0 {
			headers = append(headers, "temporal-resource-id", fmt.Sprintf("workflow:%s", val))
		}
	case *workflowservice.SignalWorkflowExecutionRequest:
		if val := r.GetWorkflowExecution().GetWorkflowId(); val != "" && len(opts.ExistingMetadata.Get("temporal-resource-id")) == 0 {
			headers = append(headers, "temporal-resource-id", fmt.Sprintf("workflow:%s", val))
		}
	case *workflowservice.StartActivityExecutionRequest:
		if val := r.GetActivityId(); val != "" && len(opts.ExistingMetadata.Get("temporal-resource-id")) == 0 {
			headers = append(headers, "temporal-resource-id", fmt.Sprintf("activity:%s", val))
		}
	case *workflowservice.StartWorkflowExecutionRequest:
		if val := r.GetWorkflowId(); val != "" && len(opts.ExistingMetadata.Get("temporal-resource-id")) == 0 {
			headers = append(headers, "temporal-resource-id", fmt.Sprintf("workflow:%s", val))
		}
	case *workflowservice.TerminateActivityExecutionRequest:
		if val := r.GetActivityId(); val != "" && len(opts.ExistingMetadata.Get("temporal-resource-id")) == 0 {
			headers = append(headers, "temporal-resource-id", fmt.Sprintf("activity:%s", val))
		}
	case *workflowservice.TerminateWorkflowExecutionRequest:
		if val := r.GetWorkflowExecution().GetWorkflowId(); val != "" && len(opts.ExistingMetadata.Get("temporal-resource-id")) == 0 {
			headers = append(headers, "temporal-resource-id", fmt.Sprintf("workflow:%s", val))
		}
	case *workflowservice.TriggerWorkflowRuleRequest:
		if val := r.GetExecution().GetWorkflowId(); val != "" && len(opts.ExistingMetadata.Get("temporal-resource-id")) == 0 {
			headers = append(headers, "temporal-resource-id", fmt.Sprintf("workflow:%s", val))
		}
	case *workflowservice.UnpauseWorkflowExecutionRequest:
		if val := r.GetWorkflowId(); val != "" && len(opts.ExistingMetadata.Get("temporal-resource-id")) == 0 {
			headers = append(headers, "temporal-resource-id", fmt.Sprintf("workflow:%s", val))
		}
	case *workflowservice.UpdateWorkflowExecutionOptionsRequest:
		if val := r.GetWorkflowExecution().GetWorkflowId(); val != "" && len(opts.ExistingMetadata.Get("temporal-resource-id")) == 0 {
			headers = append(headers, "temporal-resource-id", fmt.Sprintf("workflow:%s", val))
		}
	case *workflowservice.UpdateWorkflowExecutionRequest:
		if val := r.GetWorkflowExecution().GetWorkflowId(); val != "" && len(opts.ExistingMetadata.Get("temporal-resource-id")) == 0 {
			headers = append(headers, "temporal-resource-id", fmt.Sprintf("workflow:%s", val))
		}
	}

	return headers, nil
}
