name: ci
on:
  pull_request:
permissions:
  contents: read
jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: actions/setup-go@7b8cf10d4e4a01d4992d18a89f4d7dc5a3e6d6f4 # v4.3.0
        with:
          go-version: '^1.21'
      - uses: arduino/setup-protoc@a8b67ba40b37d35169e222f3bb352603327985b6 # v2.1.0
      - name: 'Setup jq'
        uses: dcarbone/install-jq-action@8867ddb4788346d7c22b72ea2e2ffe4d514c7bcb # v2.1.0
      - run: make ci-build
      - name: Fail if the repo is dirty
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "Detected uncommitted changes."
            git status
            git diff
            exit 1
          fi
      - name: Check for OpenAPI path conflicts
        run: go run ./cmd/check-path-conflicts/main.go openapi/openapiv2.json
