name: Push to Buf

on:
  push:
    branches:
      - master

env:
  BUF_TOKEN: ${{ secrets.BUF_API_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v4
        with:
          version: 7
      - name: Install modules
        run: pnpm install
      - name: Push Buf protos to the buf registry
        run: pnpm push
