name: Push to Buf Registry

on:
  push:
    tags:
      - 'v**'
    branches:
      - main
permissions:
  contents: read
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: bufbuild/buf-action@fd21066df7214747548607aaa45548ba2b9bc1ff # v1.4.0
        with:
          version: 1.49.0
          token: ${{ secrets.BUF_TEMPORALIO_TOKEN }}
